hold

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,102 +18,102 @@ jobs:
       with:
           fetch-depth: 1
     - name: Set environment variables
-      run: |
-          source .env
-          echo '::set-env name=TERM::xterm'
-    - name: Pull in docker images
-      run: |
-          source .env
-          docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }} &>/dev/null
-          echo ' - pull in main docker images'
-          docker pull ${XQERL_DOCKER_IMAGE}
-          docker pull ${PROXY_DOCKER_IMAGE}
-          echo ' - pull in my docker images as helpers'
-          docker pull docker.pkg.github.com/grantmacken/alpine-scour/scour:0.0.2
-          docker pull docker.pkg.github.com/grantmacken/alpine-zopfli/zopfli:0.0.1
-          docker pull docker.pkg.github.com/grantmacken/alpine-cssnano/cssnano:0.0.3
-    - name: Setup gcloud
-      uses: googlecloudplatform/github-actions/setup-gcloud@master
-      with:
-          version: "270.0.0"
-          service_account_email: ${{ secrets.client_email }}
-          service_account_key: ${{ secrets.gce_key }}
-    - name: Configure GCE project
-      run: |
-          source .env
-          echo ' - set up GCE project from .env vars '
-          gcloud config set project ${GCE_PROJECT}
-          gcloud config set compute/zone ${GCE_ZONE}
-          # gcloud compute instances list
-          gcloud compute config-ssh &>/dev/null
-          gcloud compute ssh ${GCE_NAME} --command \
-          "docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }}"
-          gcloud compute ssh ${GCE_NAME} --command \
-          "docker pull ${XQERL_DOCKER_IMAGE} && docker pull ${PROXY_DOCKER_IMAGE}"
-    - name: Check for previous deployments
-      run: |
-          source .env
-          gcloud compute ssh ${GCE_NAME} --command \
-          "ls deploy" > deployedTars.list
-          #echo ::set-env name=DEPLOYED_NGINX_CONFIGURATION::$(grep 'nginx-configuration.tar' deployedTars.list && echo 'true' || echo 'false' )
-          #echo ::set-env name=DEPLOYED_STATIC_ASSETS::$(grep 'static-assets.tar' deployedTars.list && echo 'true' || echo 'false' )
-          echo ::set-env name=DEPLOYED_XQERL_COMPILE_CODE::$(grep xqel-compiled-code deployedTars.list && echo 'true' || echo 'false' )
-          echo 
-    # - name: If deployed get previous nginx-configuration deploy hash
-    #   if:  ${{ env.DEPLOYED_NGINX_CONFIGURATION}} == 'true'
-    #   run: |
-    #      echo ' previous nginx-configuration tar exists'
-    #      source .env
-    #      gcloud compute ssh ${GCE_NAME} --command \
-    #      "docker run --rm --workdir /home --volume /home/${GCE_NAME}/deploy:/tmp \
-    #       --entrypoint 'md5sum' ${XQERL_DOCKER_IMAGE} nginx-configuration.tar" | tee deployed-nginx-configuration.hash
-    # - name: If deployed upload previous nginx-configuration hash as an artifact
-    #   if:  ${{ env.DEPLOYED_NGINX_CONFIGURATION}} == 'true'
-    #   uses: actions/upload-artifact@v1
-    #   with:
-    #     name: deployed-nginx-configuration-hash
-    #     path: deployed-nginx-configuration.hash
-    # - name: If deployed get previous static-assets deploy hash
-    #   if:  ${{ env.DEPLOYED_STATIC_ASSETS}} == 'true'
-    #   run: |
-    #      source .env
-    #      gcloud compute ssh ${GCE_NAME} --command \
-    #      "docker run --rm --volume /home/${GCE_NAME}/deploy:/tmp \
-    #       --entrypoint 'md5sum' ${XQERL_DOCKER_IMAGE} /tmp/static-assets.tar" | tee deployed-static-assets.hash
-    # - name: If deployed upload previous static-assets hash as an artifact
-    #   if:  ${{ env.DEPLOYED_STATIC_ASSETS}} == 'true'
-    #   uses: actions/upload-artifact@v1
-    #   with:
-    #     name: deployed-static-assets-hash
-    #     path: deployed-static-assets.hash
-    - name: If xqerl-compiled-code deployed get deploy hash
-      if:  ${{ env.DEPLOYED_XQERL_COMPILED_CODE }} == 'true'
-      run: |
-         source .env
-         gcloud compute ssh ${GCE_NAME} --command 'ls -al deploy'
-         gcloud compute ssh ${GCE_NAME} --command 'md5sum deploy/xqerl-compiled-code.tar' | tee xqerl-compiled-code.hashes
-    - name: Bring up the xqerl container, compile xQuery, then test restXQ routes
-      run: |
-          source .env
-          echo ' starting xqerl will also: '
-          echo ' - create the volumes we require'
-          echo ' - create the network we require'
-          make xqerl-up
-          echo ' - compile build xQuery files to run on the beam'
-          echo ' - the build artifact is the **xqerl-compiled-code.tar**'
-          make xqerl-build
-          #ls -al deploy/xqerl-compiled-code.tar
-          echo ' - take a peek at the running xqerl container instance'
-          make xqerl-info
-          echo ' - before we place a reverse proxy server before xqerl '
-          echo '   we can test our **restXQ routes** using  *curl* and '
-          echo '   the xqerl internal IPAddress and published port'
-          make xqerl-tests
-          echo ' - append a hash of newly built xqerl-compiled-code.tar to file: [ xqerl-compiled-code.hashes ] '
-          md5sum deploy/xqerl-compiled-code.tar | tee xqerl-compiled-code.hashes
-          echo ' - we only need to deploy if the md5sum hashes are different '
-          md5sum --check --status xqerl-compiled-code.hashes || echo 'OK deploy'
-          #echo ${{ env.DEPLOY_XQERL_COM }}
+      #run: |
+      #    source .env
+      #    echo '::set-env name=TERM::xterm'
+    #- name: Pull in docker images
+      #run: |
+      #    source .env
+      #    docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }} &>/dev/null
+      #    echo ' - pull in main docker images'
+      #    docker pull ${XQERL_DOCKER_IMAGE}
+      #    docker pull ${PROXY_DOCKER_IMAGE}
+      #    echo ' - pull in my docker images as helpers'
+      #    docker pull docker.pkg.github.com/grantmacken/alpine-scour/scour:0.0.2
+      #    docker pull docker.pkg.github.com/grantmacken/alpine-zopfli/zopfli:0.0.1
+      #    docker pull docker.pkg.github.com/grantmacken/alpine-cssnano/cssnano:0.0.3
+    #- name: Setup gcloud
+      #uses: googlecloudplatform/github-actions/setup-gcloud@master
+      #with:
+      #    version: "270.0.0"
+      #    service_account_email: ${{ secrets.client_email }}
+      #    service_account_key: ${{ secrets.gce_key }}
+    #- name: Configure GCE project
+      #run: |
+      #    source .env
+      #    echo ' - set up GCE project from .env vars '
+      #    gcloud config set project ${GCE_PROJECT}
+      #    gcloud config set compute/zone ${GCE_ZONE}
+      #    # gcloud compute instances list
+      #    gcloud compute config-ssh &>/dev/null
+      #    gcloud compute ssh ${GCE_NAME} --command \
+      #    "docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }}"
+      #    gcloud compute ssh ${GCE_NAME} --command \
+      #    "docker pull ${XQERL_DOCKER_IMAGE} && docker pull ${PROXY_DOCKER_IMAGE}"
+    #- name: Check for previous deployments
+      #run: |
+      #    source .env
+      #    gcloud compute ssh ${GCE_NAME} --command \
+      #    "ls deploy" > deployedTars.list
+      #    #echo ::set-env name=DEPLOYED_NGINX_CONFIGURATION::$(grep 'nginx-configuration.tar' deployedTars.list && echo 'true' || echo 'false' )
+      #    #echo ::set-env name=DEPLOYED_STATIC_ASSETS::$(grep 'static-assets.tar' deployedTars.list && echo 'true' || echo 'false' )
+      #    echo ::set-env name=DEPLOYED_XQERL_COMPILE_CODE::$(grep xqel-compiled-code deployedTars.list && echo 'true' || echo 'false' )
+      #    echo 
+    ## - name: If deployed get previous nginx-configuration deploy hash
+    ##   if:  ${{ env.DEPLOYED_NGINX_CONFIGURATION}} == 'true'
+    ##   run: |
+    ##      echo ' previous nginx-configuration tar exists'
+    ##      source .env
+    ##      gcloud compute ssh ${GCE_NAME} --command \
+    ##      "docker run --rm --workdir /home --volume /home/${GCE_NAME}/deploy:/tmp \
+    ##       --entrypoint 'md5sum' ${XQERL_DOCKER_IMAGE} nginx-configuration.tar" | tee deployed-nginx-configuration.hash
+    ## - name: If deployed upload previous nginx-configuration hash as an artifact
+    ##   if:  ${{ env.DEPLOYED_NGINX_CONFIGURATION}} == 'true'
+    ##   uses: actions/upload-artifact@v1
+    ##   with:
+    ##     name: deployed-nginx-configuration-hash
+    ##     path: deployed-nginx-configuration.hash
+    ## - name: If deployed get previous static-assets deploy hash
+    ##   if:  ${{ env.DEPLOYED_STATIC_ASSETS}} == 'true'
+    ##   run: |
+    ##      source .env
+    ##      gcloud compute ssh ${GCE_NAME} --command \
+    ##      "docker run --rm --volume /home/${GCE_NAME}/deploy:/tmp \
+    ##       --entrypoint 'md5sum' ${XQERL_DOCKER_IMAGE} /tmp/static-assets.tar" | tee deployed-static-assets.hash
+    ## - name: If deployed upload previous static-assets hash as an artifact
+    ##   if:  ${{ env.DEPLOYED_STATIC_ASSETS}} == 'true'
+    ##   uses: actions/upload-artifact@v1
+    ##   with:
+    ##     name: deployed-static-assets-hash
+    ##     path: deployed-static-assets.hash
+    #- name: If xqerl-compiled-code deployed get deploy hash
+      #if:  ${{ env.DEPLOYED_XQERL_COMPILED_CODE }} == 'true'
+      #run: |
+      #   source .env
+      #   gcloud compute ssh ${GCE_NAME} --command 'ls -al deploy'
+      #   gcloud compute ssh ${GCE_NAME} --command 'md5sum deploy/xqerl-compiled-code.tar' | tee xqerl-compiled-code.hashes
+    #- name: Bring up the xqerl container, compile xQuery, then test restXQ routes
+      #run: |
+      #    source .env
+      #    echo ' starting xqerl will also: '
+      #    echo ' - create the volumes we require'
+      #    echo ' - create the network we require'
+      #    make xqerl-up
+      #    echo ' - compile build xQuery files to run on the beam'
+      #    echo ' - the build artifact is the **xqerl-compiled-code.tar**'
+      #    make xqerl-build
+      #    #ls -al deploy/xqerl-compiled-code.tar
+      #    echo ' - take a peek at the running xqerl container instance'
+      #    make xqerl-info
+      #    echo ' - before we place a reverse proxy server before xqerl '
+      #    echo '   we can test our **restXQ routes** using  *curl* and '
+      #    echo '   the xqerl internal IPAddress and published port'
+      #    make xqerl-tests
+      #    echo ' - append a hash of newly built xqerl-compiled-code.tar to file: [ xqerl-compiled-code.hashes ] '
+      #    md5sum deploy/xqerl-compiled-code.tar | tee xqerl-compiled-code.hashes
+      #    echo ' - we only need to deploy if the md5sum hashes are different '
+      #    md5sum --check --status xqerl-compiled-code.hashes || echo 'OK deploy'
+      #    #echo ${{ env.DEPLOY_XQERL_COM }}
     # - name: Check md5 hashes of deploy tars and this build tar are different and deploy if required
     #   if:  ! env.DEPLOY_XQERL_COMPILED_CODE
     #   run: |
